# Generated by Django 5.2 on 2025-08-14 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_order_card_details_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Mobile & Accessories', 'Mobile & Accessories'), ('Computers & Laptops', 'Computers & Laptops'), ('Audio & Headphones', 'Audio & Headphones'), ('Smart Home & Wearables', 'Smart Home & Wearables'), ('Gaming & Entertainment', 'Gaming & Entertainment')], default='Mobile & Accessories', max_length=50),
        ),
    ]
